version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  # Ignore doc8 updates as at the time of writing they conflict with sphinx-toolbox.
  - dependency-name: doc8
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: daily
