language: python
python: 3.7
dist: xenial
sudo: true
before_install:
- openssl aes-256-cbc -K $encrypted_61e4bc3d8ae5_key -iv $encrypted_61e4bc3d8ae5_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- travis_retry pip install --upgrade pip setuptools
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
before_script:
script:
- isort --recursive
after_success:
- codecov
