language: python
python:
- '3.8'
matrix:
  fast_finish: true
env:
  matrix:
  - CI_PATTERN=test_database_summary.py
addons:
  apt:
    packages:
    - enchant
before_install:
- openssl aes-256-cbc -K $encrypted_61e4bc3d8ae5_key -iv $encrypted_61e4bc3d8ae5_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- travis_retry pip install --upgrade pip setuptools
install:
- travis_retry pip install --upgrade --editable .[dev]
cache: pip
before_script:
- python ci/set_secrets_file.py
script:
- python ci/run_script.py
after_success:
- codecov
