---

name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Run at 1:00 every day
    - cron: '0 1 * * *'
  workflow_dispatch: {}

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/cache@v4
        env:
          UV_CACHE_DIR: /home/runner/.cache/uv
        with:
          path: "${{ env.UV_CACHE_DIR }}"
          key: ${{ runner.os }}-uv-${{ hashFiles('pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: "Install dependencies"
        env:
          UV_CACHE_DIR: /home/runner/.cache/uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          uv venv /home/runner/.venv
          source /home/runner/.venv/bin/activate
          uv pip install --upgrade --editable .[dev]

      # We choose not to use a Python wrapper or alternative to hadolint as none
      # appear to be well maintained, and they require more setup than we would
      # want.
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/mock_vws/_flask_server/Dockerfile

      - name: "Lint"
        run: |
          source /home/runner/.venv/bin/activate
          make lint
